loss: !!python/object:gluonts.torch.modules.loss.NegativeLogLikelihood
  __dict__:
    beta: 0.0
  __fields_set__: !!set {}
  __private_attribute_values__: {}
lr: 0.001
model_kwargs:
  batch_norm: false
  context_length: 40
  distr_output: !!python/object:gluonts.torch.distributions.studentT.StudentTOutput
    __init_args__: !!python/object/apply:collections.OrderedDict
    - []
  hidden_dimensions:
  - 20
  - 20
  prediction_length: 4
weight_decay: 1.0e-08
